### ISSUE TITLE
Design light theme for Fairdrive

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairdrive-theapp#15]
A light theme for Fairdrive is needed (currently dark theme exists and is implemented).

**Comment by crtahlin** [comment]
@MichalSHAC when finished, ping @mmahmutovic to further assign implementation of #16

**Comment by MichalSHAC** [comment]
Handed over (set of new values for "Day" ser) 

Will await to see if there any snags or issues during implementation test. 

Otherwise, light theme is completed, see preview

<img width="1033" alt="Screenshot 2021-07-01 at 15 58 45" src="https://user-images.githubusercontent.com/45706231/124144629-6cc41b00-da8c-11eb-9ba5-43f74d69518f.png">
<img width="621" alt="Screenshot 2021-07-01 at 16 33 23" src="https://user-images.githubusercontent.com/45706231/124144649-70f03880-da8c-11eb-9911-a45385346c48.png">

link to figma design system page
https://www.figma.com/file/1uwKXyizhv88JvDckja7Py/?node-id=1117%3A20321
