### ISSUE TITLE
Some content items aren't found

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairdrive-theapp#284]
Some content is missing from the project and because of this, errors are displayed in the log.

Main page:
-https://app.fairdrive.fairdatasociety.org/icons/android-chrome-192x192.png

https://app.fairdrive.fairdatasociety.org/explore
-https://app.fairdrive.fairdatasociety.org/media/dapps/FDS%20AgendaLight.svg
-https://app.fairdrive.fairdatasociety.org/media/dapps/ConsentsLight.svg

**Comment by tomicvladan** [comment]
I'm not sure what are these images. @crtahlin do you know what are these?

**Comment by crtahlin** [comment]
@tomicvladan I do not know what these are specifically. 
Are they maybe in the Figma file for Fairdrive? 
https://www.figma.com/file/gjGqOHWfdfz3oU6eGo4Adu/Fairdrive---External?node-id=244%3A13278&t=uXHwuep9ab7RP8bH-1
Otherwise, please find appropriate images, can be generic, based on what they are supposed to show. Preferably in the above Figma.

**Comment by tomicvladan** [comment]
I'm not sure what they represent. But in any case I think there is no suitable images in this figma link.
