### ISSUE TITLE
err403 after reloading .dev drive

### ISSUE THREAD

**Issue by tamas6** [fairDataSociety/fairdrive-theapp#491]
related to #234 probably.

url remains: https://app.fairdrive.dev.fairdatasociety.org/overview/

**Comment by IgorShadurin** [comment]
Confirm.
-Login to https://app.fairdrive.dev.fairdatasociety.org/
-Reload the page, get error

<img width="1059" alt="Screenshot 2023-09-08 at 15 29 05" src="https://github.com/fairDataSociety/fairdrive-theapp/assets/1595061/f503d295-767f-4a99-a71d-a993cfef10d3">

**Comment by tamas6** [comment]
https://github.com/fairDataSociety/fairdrive-theapp/assets/81620050/55aec772-49dc-4e75-8e01-956e6dfe3b95


NEW case. After this, simple delete the /overview/ part of the url simulating -redirecting to login page- This happened. Spooky

**Comment by darkobas2** [comment]
There is no /overview/ in static... that shows in url works only because of js router in index   so if you reload it wants to load /overview/index.xx which doesnt exist

**Comment by darkobas2** [comment]
This is exactly what we have https://github.com/fairDataSociety/fairdrive-theapp/blob/e1c8c124cbba388567c991bb956ec6763768e693/Dockerfile#L83

$uri is a variable that contains overview in our example case. If you look in static export there is no overview file, no overview folder so that can not work. You have to change source code so that these pages are generated.

https://nextjs.org/docs/pages/building-your-application/deploying/static-exports

**Comment by IgorShadurin** [comment]
> This is exactly what we have
> 
> https://github.com/fairDataSociety/fairdrive-theapp/blob/e1c8c124cbba388567c991bb956ec6763768e693/Dockerfile#L83
> 
> $uri is a variable that contains overview in our example case. If you look in static export there is no overview file, no overview folder so that can not work. You have to change source code so that these pages are generated.
> 
> https://nextjs.org/docs/pages/building-your-application/deploying/static-exports

I looked at the build in the `out` directory. It has an `overview` directory, but there is no `index.html` in it.

Using the link you provided, what can I do to make sure everything works as it should?

I configured something similar for Apache, but nginx may require some additional configuration. The main goal is for all unfound routes to be processed by index.html

Example for Apache
```
<Directory /var/www/html>
                 Options Indexes FollowSymLinks
                 AllowOverride All
                 Require all granted

                 RewriteEngine on
                 # If the requested resource is a file (but not directory), go to it as it is
                 RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} -f
                 RewriteRule ^ - [L]
                 # For other cases (including if the directory exists but doesn't contain an index.html), use index.html
                 RewriteRule^/index.html

</Directory>
```

**Comment by darkobas2** [comment]
If overview folder exists and its empty explains why we get 403 and not 404 or index.html.

If we remove "$uri/" that will fix the 403.

We shouldnt have an empty folder produced by static export build

What ever we hack in web server the following issues will persist:

 - you cant link any "page" directly because they dont exist.
- on reload you always get login page even if you have just logged in.

**Comment by IgorShadurin** [comment]
> * on reload you always get login page even if you have just logged in.

In any case, after reloading the page, the login is reset and you need to log in again

**Comment by darkobas2** [comment]
> > * on reload you always get login page even if you have just logged in.
> 
> In any case, after reloading the page, the login is reset and you need to log in again

Dunno if we declare that a feature or a "bug"

**Comment by tamas6** [comment]
I’d prioritise this, stale issue for 3 weeks now
