### ISSUE TITLE
Enable multiple file upload

### ISSUE THREAD

**Issue by tfius** [fairDataSociety/fairdrive-theapp#499]
When upload is selected, user can do multiple file selection, but only one file is uploaded. Either disable multiple file upload or implement multiple file upload. Prefererably multiple file upload.

**Comment by tomicvladan** [comment]
Multiple file upload is implemented in this PR https://github.com/fairDataSociety/fairdrive-theapp/pull/514

But without bigger refactoring it might cause more trouble than benefits. I described the problem in the PR.

And regarding one file upload, there is no way to disable multiple file selection, because that's browser feature.
