### ISSUE TITLE
Typos & Consistency

### ISSUE THREAD

**Issue by tamas6** [fairDataSociety/fairdrive-theapp#509]
- [ ] - **Continue** button should be Login button
    - where? [main login page. ](https://app.fairdrive.dev.fairdatasociety.org/)
- [ ] - typo: Error "Username "<Invalid Username>"does not **exists**"
    - Error: "POD with name "<newpodname> already **exists**
- [ ]  - 2 almost identical error message: 

"Username is not valid."
"Username "< Invalid Username >"does not exists"

**Suggestion:** Invalid Username, Invalid Password --> in line with "Username/password is required"
 are already in use. Simple and straightforward

**Comment by tomicvladan** [comment]
For the first issue a PR is created https://github.com/fairDataSociety/fairdrive-theapp/pull/515

Regarding the other messages, they are error messages that come from other components, probably from fdp-storage.

**Comment by IgorShadurin** [comment]
Created a fix for `Username "${username}" does not exists` typo
https://github.com/fairDataSociety/fdp-storage/pull/263

Regarding text `Pod with name "${name}" already exists`

AI explanation:

In the phrase "Pod with name '${name}' already exists", the subject of the sentence is the singular noun phrase "Pod with name '${name}'". 

In English, the verb needs to agree with the subject in number (singular or plural). Since our subject is singular ("Pod"), we use the singular form of the verb, which is "exists". 

If the subject were plural, the verb would change to "exist" to maintain agreement. For instance, if we were talking about multiple pods, the sentence would be constructed as "Pods with names '${name1}', '${name2}'... already exist".

Therefore, to maintain proper grammatical structure and agreement between the subject and the verb, we use "exists" when referring to a single pod.

**Comment by tamas6** [comment]
> 1. Created a fix for `Username "${username}" does not exists` typo
>    [fix: username availability error text fdp-storage#263](https://github.com/fairDataSociety/fdp-storage/pull/263)
> 2. Regarding text `Pod with name "${name}" already exists`
> 
> AI explanation:
> 
> In the phrase "Pod with name '${name}' already exists", the subject of the sentence is the singular noun phrase "Pod with name '${name}'".
> 
> In English, the verb needs to agree with the subject in number (singular or plural). Since our subject is singular ("Pod"), we use the singular form of the verb, which is "exists".
> 
> If the subject were plural, the verb would change to "exist" to maintain agreement. For instance, if we were talking about multiple pods, the sentence would be constructed as "Pods with names '${name1}', '${name2}'... already exist".
> 
> Therefore, to maintain proper grammatical structure and agreement between the subject and the verb, we use "exists" when referring to a single pod.

Good catch, me sorry!
